### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by rossanodr** [abtp2/csPlayer#1]
Do you have any ideia on how I could use this in a react project?

**Comment by abtp2** [comment]
Well, I didn’t make this for React yet, but I’ll be adding support for it soon!

In the meantime, you can create your own video player. The trick to hide the default title and controls is [here](https://github.com/abtp2/csPlayer/blob/d45a1acd04e120d2cd7008b62419f4ae980b3c60/src/csPlayer.css#L132).
